"use client"

import { useEffect } from "react"

const SW_PATH = "/sw.js"

/**
 * Registers the workbox service worker generated by next-pwa.
 * Registration is manual because the App Router has no `main.js`
 * entry point for next-pwa to inject its register script into.
 */
export function ServiceWorkerRegistrar() {
  useEffect(() => {
    if (!("serviceWorker" in navigator)) return
    if (process.env.NODE_ENV !== "production") return

    const register = async () => {
      try {
        const registration = await navigator.serviceWorker.register(SW_PATH, {
          scope: "/",
        })

        registration.addEventListener("updatefound", () => {
          const worker = registration.installing
          worker?.addEventListener("statechange", () => {
            if (worker.state === "installed" && navigator.serviceWorker.controller) {
              // A new version is available; the workbox worker will
              // claim clients after activation (clientsClaim: true).
            }
          })
        })
      } catch (error) {
        console.error("[NEXUS] Service worker registration failed:", error)
      }
    }

    void register()
  }, [])

  return null
}
