/**
 * Lorem Ipsum generator — deterministic placeholder text.
 *
 * - Uses a seeded mulberry32 PRNG; the same seed always produces the
 *   same output. The "Randomize" option seeds from a cryptographic
 *   source (Math.random fallback when crypto is unavailable).
 * - Sentences are assembled from a fixed word corpus with "Lorem ipsum"
 *   style connective patterns and sentence-frame templates, so output is
 *   coherent-looking but never claimed to have meaning. It is placeholder
 *   text, clearly labelled as such in the UI.
 * - Output is bounded: the engine rejects quantities beyond documented
 *   maximums. HTML output is generated by this module only and contains
 *   no user input, so it is safe by construction.
 */

export type LoremMode = "paragraphs" | "sentences" | "words"
export type LoremFormat = "plain" | "markdown" | "html"

/** Documented maximums per mode (rejected before generating). */
export const LOREM_MAX: Record<LoremMode, number> = {
  paragraphs: 500,
  sentences: 2500,
  words: 10_000,
}

export const LOREM_DEFAULT_SEED = 20260810

const CORPUS = [
  "amet",
  "arcu",
  "augue",
  "bibendum",
  "commodo",
  "consequat",
  "consectetur",
  "curabitur",
  "dapibus",
  "diam",
  "dictum",
  "dignissim",
  "dolor",
  "donec",
  "dui",
  "egestas",
  "eget",
  "eleifend",
  "elementum",
  "elit",
  "enim",
  "erat",
  "eros",
  "etiam",
  "eu",
  "euismod",
  "facilisi",
  "faucibus",
  "felis",
  "fermentum",
  "feugiat",
  "finibus",
  "fringilla",
  "fusce",
  "gravida",
  "habitant",
  "hendrerit",
  "iaculis",
  "id",
  "imperdiet",
  "in",
  "integer",
  "interdum",
  "ipsum",
  "justo",
  "lacinia",
  "lacus",
  "laoreet",
  "lectus",
  "leo",
  "libero",
  "ligula",
  "lobortis",
  "lorem",
  "luctus",
  "maecenas",
  "magna",
  "malesuada",
  "massa",
  "mattis",
  "maximus",
  "metus",
  "mi",
  "molestie",
  "mollis",
  "morbi",
  "nam",
  "neque",
  "nibh",
  "nisi",
  "nisl",
  "nulla",
  "nullam",
  "odio",
  "orci",
  "ornare",
  "pellentesque",
  "pharetra",
  "pharetra",
  "placerat",
  "porta",
  "porttitor",
  "posuere",
  "praesent",
  "pretium",
  "proin",
  "pulvinar",
  "quam",
  "quis",
  "quisque",
  "rhoncus",
  "risus",
  "rutrum",
  "sagittis",
  "sapien",
  "scelerisque",
  "sed",
  "sem",
  "semper",
  "sit",
  "sodales",
  "sollicitudin",
  "suscipit",
  "suspendisse",
  "tellus",
  "tempus",
  "tincidunt",
  "tortor",
  "tristique",
  "turpis",
  "ullamcorper",
  "ultrices",
  "ultricies",
  "urna",
  "ut",
  "varius",
  "vel",
  "velit",
  "venenatis",
  "vestibulum",
  "viverra",
  "volutpat",
  "vulputate",
  "accumsan",
  "adipiscing",
  "aliquam",
  "aliquet",
  "ante",
  "aptent",
  "auctor",
  "blandit",
  "condimentum",
  "congue",
  "cras",
  "cubilia",
  "curae",
  "cursus",
]

const CONNECTIVES = [
  "ac",
  "at",
  "auctor",
  "efficitur",
  "et",
  "ex",
  "in",
  "nec",
  "non",
  "praesent",
  "quis",
  "sed",
  "ut",
]

const CLASSIC_WORDS = [
  "lorem",
  "ipsum",
  "dolor",
  "sit",
  "amet",
  "consectetur",
  "adipiscing",
  "elit",
  "sed",
  "do",
  "eiusmod",
  "tempor",
  "incididunt",
  "ut",
  "labore",
  "et",
  "dolore",
  "magna",
  "aliqua",
  "ut",
  "enim",
  "ad",
  "minim",
  "veniam",
  "quis",
  "nostrud",
  "exercitation",
  "ullamco",
  "laboris",
  "nisi",
  "ut",
  "aliquip",
  "ex",
  "ea",
  "commodo",
  "consequat",
  "duis",
  "aute",
  "irure",
  "dolor",
  "in",
  "reprehenderit",
  "in",
  "voluptate",
  "velit",
  "esse",
  "cillum",
  "dolore",
  "eu",
  "fugiat",
  "nulla",
  "pariatur",
  "excepteur",
  "sint",
  "occaecat",
  "cupidatat",
  "non",
  "proident",
  "sunt",
  "in",
  "culpa",
  "qui",
  "officia",
  "deserunt",
  "mollit",
  "anim",
  "id",
  "est",
  "laborum",
]

/** Deterministic 32-bit PRNG (mulberry32). */
export function mulberry32(seed: number): () => number {
  let state = seed >>> 0
  return () => {
    state = (state + 0x6d2b79f5) >>> 0
    let t = state
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

/** Random seed from a proper source (crypto when available). */
export function randomSeed(): number {
  if (typeof crypto !== "undefined" && typeof crypto.getRandomValues === "function") {
    const buffer = new Uint32Array(1)
    crypto.getRandomValues(buffer)
    return buffer[0] >>> 0
  }
  return Math.floor(Math.random() * 0x7fffffff)
}

export interface LoremOptions {
  mode: LoremMode
  quantity: number
  format: LoremFormat
  /** Prepend the traditional opening passage (seeded from the PRNG). */
  startWithClassic: boolean
  seed: number
}

export interface LoremResult {
  text: string
  /** Words actually generated (for stats/history summaries). */
  wordCount: number
  seed: number
}

export function generateLorem(options: LoremOptions): LoremResult {
  const { mode, quantity, format, startWithClassic, seed } = options
  const random = mulberry32(seed)
  const classic = startWithClassic ? CLASSIC_WORDS : []

  let wordCount = 0
  const chunks: string[] = []

  const takeWords = (count: number): string[] => {
    const words: string[] = []
    for (let index = 0; index < count; index += 1) {
      if (wordCount < classic.length) {
        words.push(classic[wordCount])
        wordCount += 1
      } else if (random() < 0.18) {
        words.push(CONNECTIVES[Math.floor(random() * CONNECTIVES.length)])
        wordCount += 1
      } else {
        words.push(CORPUS[Math.floor(random() * CORPUS.length)])
        wordCount += 1
      }
    }
    return words
  }

  const buildSentence = (): string => {
    const length = 8 + Math.floor(random() * 6)
    const words = takeWords(length)
    let sentence = capitalize(words[0])
    for (let index = 1; index < words.length; index += 1) {
      sentence += ` ${words[index]}`
    }
    return `${sentence}.`
  }

  const buildParagraph = (): string => {
    const sentenceCount = 4 + Math.floor(random() * 3)
    const sentences: string[] = []
    for (let index = 0; index < sentenceCount; index += 1) {
      sentences.push(buildSentence())
    }
    return sentences.join(" ")
  }

  if (mode === "words") {
    for (let index = 0; index < quantity; index += 1) {
      chunks.push(takeWords(1)[0])
    }
    if (chunks.length > 0) chunks[0] = capitalize(chunks[0])
  } else if (mode === "sentences") {
    for (let index = 0; index < quantity; index += 1) {
      chunks.push(buildSentence())
    }
  } else {
    for (let index = 0; index < quantity; index += 1) {
      chunks.push(buildParagraph())
    }
  }

  const text = assemble(format, mode, chunks)
  return { text, wordCount, seed }
}

function assemble(format: LoremFormat, mode: LoremMode, chunks: string[]): string {
  if (format === "html") {
    return chunks
      .map((chunk) => (mode === "paragraphs" ? `<p>${chunk}</p>` : `<p>${chunk}</p>`))
      .join("\n")
  }
  if (format === "markdown") {
    if (mode === "words") return chunks.join(" ")
    if (mode === "sentences") return chunks.join("\n\n")
    return chunks.join("\n\n")
  }
  if (mode === "words") return chunks.join(" ")
  if (mode === "sentences") return chunks.join("\n\n")
  return chunks.join("\n\n")
}

function capitalize(word: string): string {
  const first = word.charAt(0).toLocaleUpperCase()
  return first + word.slice(1)
}
