import { defineToolManifest } from "@/shared/manifest"

export const manifest = defineToolManifest({
  slug: "image-converter",
  title: "Image Converter",
  shortDescription: "Convert JPEG, PNG, and WebP images with full quality control.",
  description:
    "Convert between JPEG, PNG, and WebP entirely in your browser. Keep every pixel with lossless output or tune the quality slider for smaller files. Nothing is uploaded — your images stay on your device.",
  categoryId: "image",
  icon: "ArrowLeftRight",
  keywords: ["convert", "jpeg", "png", "webp", "format", "image", "transcode"],
  tags: ["image", "convert", "format"],
  featured: false,
  popular: true,
  isNew: false,
  tier: "free",
  usage: 980000,
  rating: 4.7,
  trend: "up",
  trendValue: 6.8,
  gradient: "from-gold/30 to-gold-2/5",
  version: "1.0.0",
  author: "NEXUS Tools",
  updatedAt: "2026-08-01",
  estimatedProcessing: "under 2s",
  supportedDevices: ["desktop", "tablet", "mobile"],
  supportedBrowsers: ["chrome", "firefox", "safari", "edge"],
  capabilities: [
    "file input",
    "image preview",
    "lossy and lossless output",
    "download",
    "client-side processing",
  ],
})
