// Bundles the static-config validator (TS), parses data-sheets/static.yaml
// (JSON5), validates it, and writes a committed snapshot module:
// src/lib/registry/static.generated.ts
// Usage: node scripts/build-static.mjs — exits 1 if the config is invalid.

import { build } from "esbuild"
import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { execFileSync } from "node:child_process"
import { fileURLToPath } from "node:url"
import JSON5 from "json5"

const ROOT = fileURLToPath(new URL("..", import.meta.url))
const CONFIG = resolve(ROOT, "data-sheets/static.yaml")
const SNAPSHOT = resolve(ROOT, "src/lib/registry/static.generated.ts")
const CACHE = resolve(ROOT, "node_modules/.cache/static-config-bundle.mjs")

const raw = readFileSync(CONFIG, "utf8")
let config
try {
  config = JSON5.parse(raw)
} catch (error) {
  console.error(`build-static: cannot parse data-sheets/static.yaml: ${error.message}`)
  process.exit(1)
}

await build({
  entryPoints: [resolve(ROOT, "src/lib/registry/validate-entry.ts")],
  bundle: true,
  format: "esm",
  platform: "node",
  outfile: CACHE,
  logLevel: "silent",
  external: ["js-yaml", "json5"],
})

const modulePath = resolve(ROOT, "src/lib/registry/validate-entry.ts")
void modulePath

const problems = execFileSync(
  process.execPath,
  ["-e", `import("${CACHE}").then(async (m) => console.log(JSON.stringify(m.validateStaticConfig(${JSON.stringify(config)}))))`],
  { encoding: "utf8" },
).trim()
const problemsList = JSON.parse(problems)
if (problemsList.length > 0) {
  console.error("build-static: static.yaml is invalid:")
  for (const problem of problemsList) console.error(`  - ${problem}`)
  process.exit(1)
}

const source = `// GENERATED by scripts/build-static.mjs — do not edit by hand.
// Snapshot of data-sheets/static.yaml (JSON5), validated at build time.
export interface StaticToolDeclGenerated {
  id: string
  title: string
  subtitle?: string
  category: string
  icon: string
  accent: string
  entryPoint: string
  description: string[]
  examples: Array<{ label: string; input: string; params?: Record<string, string> }>
  hint?: string
  defaultInput?: string
  params?: Array<{ key: string; label: string; defaultValue?: string; options?: Array<{ value: string; label?: string }>; helpText?: string }>
  presets?: Array<{ label: string; input?: string; params?: Record<string, string> }>
  emptyInputPlaceholder?: string
  faq: Array<{ q: string; a: string[] }>
  limits?: string[]
  disabled?: boolean
}

export const STATIC_CONFIG: StaticToolDeclGenerated[] = ${JSON.stringify(config.tools, null, 2)}
`
mkdirSync(dirname(SNAPSHOT), { recursive: true })
writeFileSync(SNAPSHOT, source)
console.log(`build-static: wrote ${config.tools.length} static tool(s) to ${SNAPSHOT}`)